### PR TITLE
`Sequence` fixes

### LINKED ISSUE #63: Infinite recursion when calling `len` or `list` on a finite `Sequence`
When trying to evaluate the length or collect a new (finite) `Sequence` into a list, infinite recursion resulting in a `RecursionError`.

Example code to reproduce:

```hy
(require hyrule [seq])
(import hyrule [end-sequence])
(list (seq [n] (if (< n 5) n (end-sequence))))
```

It may also be useful to set the maximum recursion depth to a lower value for debugging:

```hy
(import sys)
(sys.setrecursionlimit 100)
```

This error is caused as follows:

1. The new `Sequence` is created, and during `__init__` it sets `high-water` to `-1`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L49
2. When calling `len` or `list` (which calls `__len__`), local variable `index` is set to `high-water` = `-1`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L78
3. `__getitem__` is called with `n` = `-1`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L80
4. When `n` is negative, `__getitem__` calls `len`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L56-L59
5. Since `high-water` is still `-1`, step 2 onwards repeats.

### LINKED ISSUE #65: `Sequence` does not support slicing properly
There are various issue with slicing a `Sequence`.

For conviencience when debugging:

```hy
(require hyrule [seq defseq])
(import hyrule [Sequence end-sequence])
```

- Does not work when `stop` is `None`:
  ```hy
  => (for [x (cut (seq [n] n) 5 None)] (print x))
  ...
  TypeError: 'NoneType' object cannot be interpreted as an integer
  ```
- Negative step sizes are not comparable with lists:
  ```hy
  => (cut [0 1 2 3 4 5 6 7 8 9] None 0 -1)
  [9 8 7 6 5 4 3 2 1]
  => (list (cut (seq [n] (if (< n 10) n (end-sequence))) None 0 -1))
  []
  ```

Probably a couple of others I missed, too.

### PR DESCRIPTION
**Pull request by Jlobblet**
Fixes #63. Fixes #65.

Also contains a few minor tweaks (removing redundant docstrings and cleaning some of the docs up a bit).

### CODE REVIEW

**Comment by Kodiologist** [comment]
```
; If any of the components are negative, the full Sequence must be
; evaluated so it can be iterated in reverse or with reference to the
; end of the Sequence
```

I think this isn't lazy enough in the case of a negative step size. Consider something like `(cut (seq [n] n) 6 2 -1)`.

Look out for trailing whitespace. You can set Git to highlight trailing whitespace in diff lines, which is handy. Also, I don't think it makes sense to change `import` to 1-space indents when the rest of the file is using 2-space indents. Your other spacing changes seem to generally make sense, but spacing changes to existing code without accompanying content changes should be in their own commit to cut down on noisy diff lines in the content commits.

I find the tests still fairly messy, but that's probably something I should do my own PR for instead of telling you what to do.

**Comment by Jlobblet** [comment]
> I think this isn't lazy enough in the case of a negative step size. Consider something like `(cut (seq [n] n) 6 2 -1)`.

Good example, will incorporate.

> Look out for trailing whitespace. You can set Git to highlight trailing whitespace in diff lines, which is handy. Also, I don't think it makes sense to change `import` to 1-space indents when the rest of the file is using 2-space indents. Your other spacing changes seem to generally make sense, but spacing changes to existing code without accompanying content changes should be in their own commit to cut down on noisy diff lines in the content commits.

Any formatting changes have just originated from using https://github.com/hylang/vscode-hy for formatting — I'll give it another pass to clean up in a separate commit.

> I find the tests still fairly messy, but that's probably something I should do my own PR for instead of telling you what to do.

Yeah, I don't like them much either. It's probably worth distilling the issues into a list so that it can be actioned more easily.

**Comment by Kodiologist** [comment]
Hmm, if vscode-hy is adding trailing whitespace, that's probably a bug.

**Comment by Jlobblet** [comment]
Another example to consider: `(cut (list (range 15)) 5 None -1)` (or equivalently using a `seq`).

**Comment by Kodiologist** [comment]
Is this still happening?

**Comment by Kodiologist** [comment]
Okay, no problem.

**Pull request closed without merging**
