### PR TITLE
Reader macro `#/` that wraps `hy.M`

### PR DESCRIPTION
**Pull request by scauligi**
Following up from https://github.com/hylang/hy/pull/2426, but moving here to hyrule.

### CODE REVIEW

**Comment by Kodiologist** [comment]
You have some extra quote marks in the docstring for `/`. Remember, Hy doesn't actually support triple-quoted strings.

Expand the docstring a bit to show how the syntax differs from that of `hy.M`. Link to `hy.M` in the Hy manual. Also, given the way the manual works at the moment, you need to explicitly list your new reader macro under `hyrule.macrotools` to get the docstring to show up. Sorry about that.

Generally I'd suggest using `setv` in place of `let` when you don't need `let`'s special magic. Also, it looks like the last three assignments can be combined into ``imp `(hy.M ~(hy.mangle (.replace mod "/" ".")))``.

Add a test for a name that needs mangling. I think your implementation is correct and the test will pass.

**Comment by scauligi** [comment]
> You have some extra quote marks in the docstring

Woops, that was a copy-paste from the Python implementation. Fixed.

> Expand the docstring a bit ...

Done! Hopefully this looks better.

> I'd suggest using `setv` in place of `let` ...

Noted and changed!

> Add a test for a name that needs mangling

Done!

**Comment by Kodiologist** [comment]
Shouldn't it be `highlight_language = "hylang"`?

**Review by Kodiologist — APPROVED** [review]

**Comment by scauligi** [comment]
...hunh, that indeed works.

We should probably update the `conf.py` in Hy then too, since I copied the `clojure` line from there.

**Pull request merged**
