### PR TITLE
Fix for `defmacro!` fails with `return`

### LINKED ISSUE #76: `defmacro!` fails with `return`
Consider something like

```hy
(require hyrule [defmacro!])

(defmacro! m [o!n]
 (return `(+ ~g!n ~g!n ~g!n)))

(defn f []
  (print "hi")
  2)

(print (m (f)))
```

This produces `NameError: name '_hy_gensym_n_1' is not defined`. The problem is that `defmacro!` expects the given body to only return implicitly. A wrapper function is probably needed to account for `return`.

### PR DESCRIPTION
**Pull request by scauligi**
Fixes #76.

...and by "make a formal PR next week" clearly I meant "next month". Welp, better late than never.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Looks like you're still doing `(require hyrule.macrotools [defmacro/g! :as ~dg])`. I'm surprised that doesn't crash.

Shouldn't `res` be a gensym?

**Comment by scauligi** [comment]
.......................this PR is embarrassing, and I'm apparently more sleep-deprived than I though.
please hold while I *actually* remove `defmacro/g!` (and yes, I believe you're correct that `res` should indeed be a gensym itself).

**Comment by scauligi** [comment]
hold on still need to gensym `res`; it's not easy to collide with it due to all the lambdas/quasiquoting, but theoretically you can use `nonlocal` from the macro body to get at it

**Comment by Kodiologist** [comment]
I'm not entirely clear why `(defmacro! m [] res 1) (m)` and `(defmacro! m [] (nonlocal res) res) (m)` raise errors. I guess it has to do with your scoping code, and I hope it's a feature and not a bug. But it does seem clear that `(defmacro! m [] (nonlocal res) 1) (m)` should be an error and isn't. Contrast with `(defmacro! m [] (nonlocal foobar) 1) (m)`, which raises `HyEvalError`. So it looks like you do need the gensym.

**Comment by scauligi** [comment]
Aha. Yep, those first two examples are raising the "correct" errors (using res before it's assigned) but from the user's perspective they should instead be raising variable unbound. I've made it a gensym.

I also just want to take a moment to say that macros that create macros are brainbending and
```hy
  `(defmacro ~name ~args
     ~docstring
     (setv ~@gensyms
           ~g!res ((fn [] ~@body)))
     `(do
        (setv ~~gs ~~os)
        ~~g!res))
```
is a cursed incantation. (although it's fun to see all the variables waving at me)

**Comment by Kodiologist** [comment]
Yeah, it's remarkable how quickly macro-writing macros, or just nested backticks, can get mentall overwhelming, especially when the goal isn't very complicated.

Are you sure you want to name the gensym with an initial `g!`? This kind of gives the impression you're implementing `defmacro!` recursively or something.

**Comment by Kodiologist** [comment]
Actually, I have a few ideas for cleanup, so let me just push a new commit and we'll see what you think.

**Comment by Kodiologist** [comment]
@scauligi If this is okay, I'll rebase and merge. Let me know.

**Comment by scauligi** [comment]
Yup, the changes look good to me, thanks for the cleanup!

**Pull request merged**
