### PR TITLE
Add a macro `block`

### PR DESCRIPTION
**Pull request by Kodiologist**

### CODE REVIEW

**Comment by allison-casey** [comment]
I'm generally opposed to giving something an abbreviated name like `retf`. if you have to mention in the docstring that it stands for `("return from")` then it should just be named `return-from`(it's even called `return-from` in common lisp). It's more explicit and readily understandable when trying to parse what a chunk of code is doing.

I'm also not a fan of allowing anonymous blocks via `None`. It leads to strange and hard to track control flow especially when you add in the `ret` alias. That's not a feature of Common Lisp's `block` and I think it's for good reason. 

I do like the solution though. Feels like a nice extension of Python's existing `return` syntax, just extended for the lispyness of Hy.

**Comment by Kodiologist** [comment]
A slightly more general feature that `block` is similar to is Perl's loop labels. `next` and `last` (equivalent to `continue` and `break`) are typically used without a label, to affect the innermost containing loop, but if you label a loop, then you can say `next LABEL` or `last LABEL` to affect that loop, no matter how many other loops you're nested in. You'd only label a loop, instead of using an anonymous loop, if you actually needed the label to disambiguate, right? That's how I think of it.

**Comment by allison-casey** [comment]
woops that's my bad, egg on face, completely misread the common lisp spec and I see the reasoning now. I still dislike using `retf` though. It gives me flashbacks to c's `printf, sprintf, fprintf` wackiness. It's a shame there isn't really any other idiomatic name for returning things besides `return`. Can we rename `retf` to `ret-from` and call it a day?

**Comment by scauligi** [comment]
Hmm, to me using `ret`/`retf` makes me think we're exiting from the surrounding function in some way rather than just a block.
What about something like `break-with` or `break-from`?
Other alternatives: `bbreak` (for "block break"), `breakv` (break-with-value, mimicking `setv`)

**Comment by Kodiologist** [comment]
`ret` and `ret-from` seem fine to me. Some form of "break" also makes sense because in some ways this operation is more like `break` than `return`. On the other hand, it can return a value, unlike `break`. On the third hand, in most cases you'll be using it only for flow control and the value won't matter, so you'll omit it. So I think I'd rather use `ret` and `ret-from`, which capture the sense of "break out of a construct and return a value which you may or may not care about". Is that okay, Sunjay?

**Comment by Kodiologist** [comment]
Once we settle on the names, I think I'll edit the documentation to describe `ret` and anonymous blocks first and `ret-from` and named blocks second, the idea being to describe the more common case first.

**Comment by allison-casey** [comment]
Scauligi makes a good point. `block-ret` and `block-ret-from` is another option. A bit verbose, but there's no ambiguity about what kind of *"return"* we're dealing with (and `block-ret-from` is the less common case anyways). Also `ret` is a very common var name in the compiler which seems to make the case for something less prone to shadowing a common var name.

**Comment by Kodiologist** [comment]
And the plot thickens. Okay, `block-ret` and `block-ret-from` seem reasonable, and it is helpfully mnemonic that they begin with "block". What say you, Sunjay?

**Comment by Kodiologist** [comment]
Done. I also corrected some indentation and made a tiny simplification to the implementation.

**Comment by allison-casey** [comment]
sold! for one PR approval to the man in the front row.

**Review by allison-casey — APPROVED** [review]

**Comment by allison-casey** [comment]
Also this turns hylang/hy#2194 into a `docme` right?

**Comment by Kodiologist** [comment]
Yep, I expect to do that shortly. The hard part will be writing the Intersphinx link to `block`, because getting Intersphinx to work is the true riddle of the modern sphinx.

**Pull request merged**
