### PR TITLE
drop support for python3.6

### PR DESCRIPTION
**Pull request by allison-casey**

### CODE REVIEW

**Review by Kodiologist — APPROVED** [review]

**Comment by allison-casey** [comment]
can I just merge this? it's a pretty minor change to bring hyrule in line with hy.

**Comment by Kodiologist** [comment]
Yeah, go for it.

**Comment by allison-casey** [comment]
oh lol i don't think i have write access in `hyrule` right now.

**Comment by Kodiologist** [comment]
Oops, I thought I'd already given the core team write access. Try again.

**Pull request merged**
