### PR TITLE
Precompile hy files

### LINKED ISSUE #42: Hyrule isn't using bytecode files
Hello!

As in the title; I tried using the master versions as well, and the issue persists. Removing `hyrule` imports and requires from my module, while keeping all other modules, sped up the import of my module.

Sorry if this isn't the place for this, as I don't know whether this counts as a bug or not.

Thank you kindly for the help!

### PR DESCRIPTION
**Pull request by scauligi**
Actually fix #42. See https://github.com/hylang/hy/pull/2299.

### CODE REVIEW

**Comment by scauligi** [comment]
wut.

**Comment by scauligi** [comment]
For whatever reason, pip is trying to build a wheel to install `hy` as a setup dependency, even when `wheel` isn't installed. Obviously this is unsuccessful. Time to dig into pip internals. <sub>again.</sub>

**Comment by Kodiologist** [comment]
I don't envy you.

**Comment by Kodiologist** [comment]
@scauligi Is this happening? I'd like to have it for the next release of Hy, but I also want to release this month. If you don't expect to finish this soon, I should probably pick it up.

**Comment by scauligi** [comment]
It's still happening! I had to give a conference talk yesterday but now that that's out of the way I can dig into delicious Python internals again.

**Comment by scauligi** [comment]
Welp, looks like the easiest way to fix this<sup>1</sup> is just to add "wheel" to hy's (yes *hy's*, not hyrule's) `setup_requires`.

A better solution would probably be to add a custom build backend to hy that we can then specify/activate through a `pyproject.toml` file, which would also make it easy for projects like hyrule to just swap in the hy build backend instead of adding boilerplate to `setup.py`.
But we can do that later.

<sup>1</sup>It works for a bunch of various configurations on my machine, at least. Experience has shown that this does not always mean it works on CI.

**Comment by Kodiologist** [comment]
```diff
 # both setup_requires and install_requires
 # since we need to compile .hy files during setup
 requires = [
-    'hy @ git+https://github.com/hylang/hy@master#egg=hy',
+    'hy @ git+https://github.com/scauligi/hy@the_wheel_deal#egg=hy',
 ]
```

Nice, it works.

>  add "wheel" to hy's (yes *hy's*, not hyrule's) `setup_requires`.

But you added it to Hyrule, too, in this PR. Is that a mistake?

**Comment by scauligi** [comment]
> Nice, it works on GitHub.

Heck yeah, awesome!

> But you added it to Hyrule, too, in this PR. Is that a mistake?

For hyrule itself, we only need wheel in hy's `setup_requires`.

I added it to hyrule's as well, since otherwise the same thing will likely happen should anyone else require hyrule as a setup dependency in their own hy-based project.

**Comment by Kodiologist** [comment]
Oh, that makes sense.

**Comment by Kodiologist** [comment]
Thanks for wrapping this up. By the way, it looks like GitHub is no longer seeing the link between your commits and your GitHub account. It probably has to do with your email address.

**Pull request merged**
