### PR TITLE
Import `Sequence` for macros in `hyrule.sequences`

### PR DESCRIPTION
**Pull request by Jlobblet**
Addresses #61.

### CODE REVIEW

**Comment by Kodiologist** [comment]
Looks pretty good. Add to NEWS and AUTHORS per CONTRIBUTING.rst.

**Comment by Kodiologist** [comment]
Oh right, also, you need to use the word "Fixes" or "Closes" followed by the issue number in order for GitHub to automagically close the corresponding issue when the PR is merged. "Addresses" won't do it. You can just edit your first comment.

**Comment by Jlobblet** [comment]
> Looks pretty good. Add to NEWS and AUTHORS per CONTRIBUTING.rst.

Will do!

> Oh right, also, you need to use the word "Fixes" or "Closes" followed by the issue number in order for GitHub to automagically close the corresponding issue when the PR is merged. "Addresses" won't do it. You can just edit your first comment.

I avoided using either of those to not invoke that behaviour as I know some people don't like it — will amend. Alternately I believe you can link the PR to the issue under the "Development" section on the right hand pane.

**Review by Kodiologist — APPROVED** [review]

**Comment by Kodiologist** [comment]
Welcome to the Hyve!

I like yeen.land uwu

**Pull request merged**
